apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-system
  namespace: capi-system
  labels:
    kustomize.toolkit.fluxcd.io/name: capi-system
    kustomize.toolkit.fluxcd.io/namespace: capi-system
  finalizers:
  - finalizers.fluxcd.io
spec:
  force: false
  interval: 10m0s
  path: ./base/capi-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-cluster
    namespace: flux-system
