apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capv-system
  namespace: capv-system
  labels:
    kustomize.toolkit.fluxcd.io/name: capv-system
    kustomize.toolkit.fluxcd.io/namespace: capv-system
  finalizers:
  - finalizers.fluxcd.io
spec:
  force: false
  interval: 10m0s
  path: ./base/capv-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-cluster
    namespace: flux-system
  postBuild:
    substituteFrom:
    - kind: Secret
      name: vsphere-credentials
