apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: load-balancer-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.26.0.60-10.26.0.70
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: load-balancer
  namespace: metallb-system
spec:
  ipAddressPools:
  - load-balancer-ip-pool
