apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- cloudflare-api-key-secret.yaml
- letsencrypt-cluster-issuer.yaml
- namespace.yaml
- sync.yaml
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: cert-manager
